spring:
  batch:
    jdbc:
      initialize-schema: embedded
      platform: h2
    job:
      enabled: true
  datasource:
    url: jdbc:h2:mem:sample;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS Schema
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
      hikari:
        poolName: Hikari
        auto-commit: false
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    defer-datasource-initialization: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: xdiinweb-posts
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: xdiinweb-posts
      heartbeat-interval: 3000ms
      max-poll-records: 500
      properties:
        spring.json.trusted.packages: 'io.github.susimsek.springbatchsamples.model'

post:
  info:
    cron:
      expression: '*/10 * * * * *'