spring:
  batch:
    jdbc:
      initialize-schema: embedded
      platform: h2
    job:
      enabled: true
      name: postInfoJob
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
      hikari:
        poolName: Hikari
        auto-commit: false
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate.cache.redisson.entity.expiration.time_to_live: 3600000
  kafka:
    template:
      default-topic: xdiinweb-posts
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: xdiinweb-posts
      heartbeat-interval: 3000ms
      max-poll-records: 500
      properties:
        spring.json.trusted.packages: 'io.github.susimsek.springbatchsamples.model'

logging:
  level:
    ROOT: INFO
    io.github.susimsek.springbatchsamples: INFO