spring:
  application:
    name: spring-batch-service
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: async-task-
      pool:
        core-size: 10
        max-size: 10
        queue-capacity: 10000
  jpa:
    open-in-view: false
    properties:
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.redisson.fallback: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
