version: '3.8'

volumes:
  mongodb:

networks:
  backend:
    name: backend

services:
  spring-batch-service:
    image: suayb/spring-batch-samples:latest
    restart: unless-stopped
    container_name: spring-batch-service
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_KAFKA_BOOTSTRAP_SERVERS
      - SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
      - SECURITY_AUTHENTICATION_TOKEN_PUBLIC_KEY
      - SECURITY_AUTHENTICATION_TOKEN_PRIVATE_KEY
      - SECURITY_AUTHENTICATION_TOKEN_ACCESS_TOKEN_VALIDITY_IN_SECONDS
      - SECURITY_AUTHENTICATION_TOKEN_REFRESH_TOKEN_VALIDITY_IN_SECONDS
      - SECURITY_AUTHENTICATION_TOKEN_COOKIE_DOMAIN
      - SECURITY_CIPHER_BASE64_SECRET
      - SECURITY_AUTHENTICATION_SECURITY_MATCHER_IGNORE_PATTERNS
      - SECURITY_AUTHENTICATION_SECURITY_MATCHER_PERMIT_ALL_PATTERNS
      - SECURITY_CONTENT_SECURITY_POLICY
      - RECAPTCHA_ENABLED
      - RECAPTCHA_VERIFY_URL
      - RECAPTCHA_SECRET_KEY
      - RECAPTCHA_THRESHOLD
      - CHATGPT_BASE_URL
      - CHATGPT_SECRET_KEY
      - CHATGPT_GPT_MODEL
      - CHATGPT_AUDIO_MODEL
      - CHATGPT_MODERATION_MODEL
      - CHATGPT_TEMPERATURE
      - CHATGPT_MAX_TOKENS
      - CHATGPT_IMAGE_NUMBER
      - CHATGPT_IMAGE_SIZE