version: '3.8'

volumes:
  mongodb:

networks:
  backend:
    name: backend

services:
  spring-batch-service:
    image: suayb/spring-batch-samples:latest
    restart: no
    container_name: spring-batch-service
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_KAFKA_BOOTSTRAP_SERVERS
      - SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC
      - SPRING_DATA_REDIS_HOST
      - SPRING_DATA_REDIS_PORT
      - SPRING_DATA_REDIS_DATABASE
      - SPRING_DATA_REDIS_PASSWORD
      - CRON_EXPRESSION_POST-INFO