version: '3.8'

volumes:
  redis:

networks:
  backend:
    name: backend

services:
  redis:
    image: redis:7.0.4-alpine
    restart: unless-stopped
    container_name: redis
    networks:
      - backend
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=d41d8cd98f00b204e9800998ecf8427e
    volumes:
      - redis:/data
    ports:
      - "6380:6379"