CREATE TABLE post (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  title VARCHAR(40) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  status VARCHAR(40) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  version INTEGER
);