replicaCount: 1

extraConfig: "autoCreateTopicsEnable=true;deleteTopicEnable=false"

controller:
  replicaCount: 1
  controllerOnly: true
  persistence:
    size: 50M
  logPersistence:
    enabled: false

broker:
  persistence:
    size: 50M
  logPersistence:
    enabled: false

kraft:
  enabled: true
  clusterId: "s_vb8yLzRnyOVW3Ko2mUbg"

image:
  repository: bitnami/kafka
  tag: 3.5.1-debian-11-r44

zookeeper:
  enabled: false

metrics:
  kafka:
    enabled: false
  serviceMonitor:
    enabled: false
    labels:
      release: prometheus

listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: PLAINTEXT
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: PLAINTEXT
  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: PLAINTEXT

externalAccess:
  enabled: true
  service:
    type: ClusterIP
