replicaCount: 1
autoCreateTopicsEnable: true
deleteTopicEnable: false

controller:
  replicaCount: 1
  controllerOnly: true
  zookeeperMigrationMode: true
  persistence:
    size: 50M

broker:
  persistence:
    size: 50M

kraft:
  enabled: true
  clusterId: "s_vb8yLzRnyOVW3Ko2mUbg"

image:
  repository: bitnami/kafka
  tag: 3.5.1-debian-11-r44


persistence:
  size: 50M

volumePermissions:
  enabled: true

zookeeper:
  enabled: false

metrics:
  kafka:
    enabled: false
  serviceMonitor:
    enabled: false
    labels:
      release: prometheus