apiVersion: batch/v1
kind: Job
metadata:
  name: spring-batch-service
  labels:
    {{- include "spring-batch-service.labels" . | nindent 4 }}
spec:
  {{- if .Values.springBatchService.parallelism }}
  parallelism: {{ .Values.springBatchService.parallelism }}
  {{- end }}
  {{- if .Values.springBatchService.completions }}
  completions: {{ .Values.springBatchService.completions }}
  {{- end }}
  backoffLimit: {{ .Values.springBatchService.backoffLimit | default 0 }}
  {{- if .Values.springBatchService.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.springBatchService.activeDeadlineSeconds }}
  {{- end }}
  {{- if .Values.springBatchService.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.springBatchService.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "spring-batch-service.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.springBatchService.restartPolicy | default "Never" }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.global.imagePullSecrets | nindent 4 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.springBatchService.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.springBatchService.extraSideContainers }}
        {{ tpl .Values.springBatchService.extraSideContainers . | indent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.springBatchService.image.repository }}:{{ .Values.springBatchService.image.tag }}"
          imagePullPolicy: {{ .Values.springBatchService.image.pullPolicy }}
          {{- if .Values.springBatchService.command }}
          command:
          {{ tpl .Values.springBatchService.command . | indent 12 }}
          {{- end }}
          {{- if .Values.springBatchService.resources }}
          resources: {{- toYaml .Values.springBatchService.resources | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.springBatchService.securityContext | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles.active }}
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: spring-batch-service-config
          volumeMounts:
          {{- if .Values.springBatchService.extraVolumeMounts }}
          {{- toYaml .Values.springBatchService.extraVolumeMounts | nindent 12 }}
      {{- end }}
      {{- if .Values.springBatchService.extraInitContainers }}
      initContainers:
      {{ tpl .Values.springBatchService.extraInitContainers . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.springBatchService.extraVolumes }}
      {{- toYaml .Values.springBatchService.extraVolumes | nindent 8 }}
  {{- end }}